rule run_happi:
    input:
        script = 'run_happi.R',
        data = '',
    params:
        outcome = '',
        quality_var = '',
        covariate = '',
        min_iterations = 15,
        max_iterations = 1000,
        method = 'splines',
        firth = 'TRUE',
        spline_df = 3,
        perm = 'FALSE',
        nstarts = 1,
        seed = 8,
    output:
        data = 'my_results.csv',
    shell:
        "Rscript {input.script} \
        --input {input.data} \
        --output {output.data} \
        --outcome {params.outcome} \
        --quality_var = {params.quality_var} \
        --covariate = {params.covariate} \
        --minit = {params.min_iterations} \
        --maxit = {params.max_iterations} \
        --method = {params.method} \
        --firth = {params.firth} \
        --spline_df = {params.spline_df} \
        --perm = {params.perm} \
        --nstarts = {params.nstarts} \
        --seed = {params.seed}"
